import {
  type Database,
  forecastSettings,
  installmentSchedules,
  loanPaymentSchedules,
  monthlyForecasts,
  payrollLines,
  payrollProfiles,
  recurringRules,
  transactions,
} from "@acc/db";
import { and, eq, gte, lt } from "drizzle-orm";
import { getBaseCurrency } from "./currency";
import { computeNetWorth } from "./net-worth";
import { sumPayrollLines } from "./payroll";

export interface ForecastMonthRow {
  month: string;
  livingExpenseMinor: bigint;
  isActual: boolean;
  scheduledIncomeMinor: bigint;
  scheduledExpenseMinor: bigint;
  netCashflowMinor: bigint;
  projectedNetWorthMinor: bigint;
}

export interface AssetForecast {
  baseCurrency: string;
  currentNetWorthMinor: bigint;
  defaultLivingExpenseMinor: bigint;
  horizonMonths: number;
  months: ForecastMonthRow[];
}

function monthStart(year: number, monthIndex: number): Date {
  return new Date(year, monthIndex, 1);
}

function formatMonthKey(d: Date): string {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  return `${y}-${m}`;
}

function monthIso(d: Date): string {
  return `${formatMonthKey(d)}-01`;
}

async function getOrCreateSettings(db: Database, userId: string) {
  const [existing] = await db
    .select()
    .from(forecastSettings)
    .where(eq(forecastSettings.userId, userId))
    .limit(1);

  if (existing) return existing;

  const currency = getBaseCurrency();
  const [created] = await db
    .insert(forecastSettings)
    .values({ userId, currency, defaultLivingExpenseMinor: 0n })
    .returning();
  return created!;
}

async function sumScheduledMonthly(
  db: Database,
  userId: string,
): Promise<{ income: bigint; expense: bigint }> {
  let income = 0n;
  let expense = 0n;

  const profiles = await db
    .select()
    .from(payrollProfiles)
    .where(and(eq(payrollProfiles.userId, userId), eq(payrollProfiles.active, true)));

  for (const profile of profiles) {
    const lines = await db
      .select()
      .from(payrollLines)
      .where(eq(payrollLines.profileId, profile.id));
    income += sumPayrollLines(lines).netMinor;
  }

  const rules = await db
    .select()
    .from(recurringRules)
    .where(and(eq(recurringRules.userId, userId), eq(recurringRules.active, true)));

  for (const rule of rules) {
    if (rule.frequency !== "monthly") continue;
    if (rule.kind === "income") income += rule.amountMinor;
    else expense += rule.amountMinor;
  }

  const installments = await db
    .select()
    .from(installmentSchedules)
    .where(and(eq(installmentSchedules.userId, userId), eq(installmentSchedules.active, true)));

  for (const inst of installments) {
    if (inst.totalPeriods != null && inst.completedPeriods >= inst.totalPeriods) continue;
    expense += inst.amountMinor;
  }

  const loans = await db
    .select()
    .from(loanPaymentSchedules)
    .where(and(eq(loanPaymentSchedules.userId, userId), eq(loanPaymentSchedules.active, true)));

  for (const loan of loans) {
    expense += loan.amountMinor;
  }

  return { income, expense };
}

export async function computeAssetForecast(
  db: Database,
  userId: string,
): Promise<AssetForecast> {
  const settings = await getOrCreateSettings(db, userId);
  const nw = await computeNetWorth(db, userId);
  const scheduled = await sumScheduledMonthly(db, userId);

  const overrides = await db
    .select()
    .from(monthlyForecasts)
    .where(eq(monthlyForecasts.userId, userId));

  const overrideByMonth = new Map(
    overrides.map((o) => [o.month.slice(0, 7), o]),
  );

  const now = new Date();
  let running = nw.totalMinor;
  const months: ForecastMonthRow[] = [];

  for (let i = 0; i < settings.horizonMonths; i++) {
    const d = monthStart(now.getFullYear(), now.getMonth() + i);
    const key = formatMonthKey(d);
    const override = overrideByMonth.get(key);

    const living =
      override?.livingExpenseMinor ?? settings.defaultLivingExpenseMinor;
    const isActual = override?.isActual ?? false;

    const netCashflow =
      scheduled.income - scheduled.expense - living;
    running += netCashflow;

    months.push({
      month: key,
      livingExpenseMinor: living,
      isActual,
      scheduledIncomeMinor: scheduled.income,
      scheduledExpenseMinor: scheduled.expense,
      netCashflowMinor: netCashflow,
      projectedNetWorthMinor: running,
    });
  }

  return {
    baseCurrency: settings.currency,
    currentNetWorthMinor: nw.totalMinor,
    defaultLivingExpenseMinor: settings.defaultLivingExpenseMinor,
    horizonMonths: settings.horizonMonths,
    months,
  };
}

/** Living expense = manual expenses not generated by payroll / recurring / installments. */
export async function syncLivingExpenseFromLedger(
  db: Database,
  userId: string,
  monthKey: string,
): Promise<{ livingExpenseMinor: bigint }> {
  const [y, m] = monthKey.split("-").map(Number);
  const start = new Date(y!, m! - 1, 1);
  const end = new Date(y!, m!, 1);

  const txs = await db
    .select({
      type: transactions.type,
      amountMinor: transactions.amountMinor,
      recurringRuleId: transactions.recurringRuleId,
      installmentScheduleId: transactions.installmentScheduleId,
      note: transactions.note,
    })
    .from(transactions)
    .where(
      and(
        eq(transactions.userId, userId),
        gte(transactions.occurredAt, start),
        lt(transactions.occurredAt, end),
      ),
    );

  let living = 0n;
  for (const t of txs) {
    if (t.type !== "expense") continue;
    if (t.recurringRuleId || t.installmentScheduleId) continue;
    if (t.note?.startsWith("月薪 ·")) continue;
    living += t.amountMinor;
  }

  const monthIsoDate = monthIso(start);
  await db
    .insert(monthlyForecasts)
    .values({
      userId,
      month: monthIsoDate,
      livingExpenseMinor: living,
      isActual: true,
    })
    .onConflictDoUpdate({
      target: [monthlyForecasts.userId, monthlyForecasts.month],
      set: {
        livingExpenseMinor: living,
        isActual: true,
        updatedAt: new Date(),
      },
    });

  return { livingExpenseMinor: living };
}

export async function upsertLivingEstimate(
  db: Database,
  userId: string,
  monthKey: string,
  amountMinor: bigint,
): Promise<void> {
  const [y, m] = monthKey.split("-").map(Number);
  const monthIsoDate = monthIso(new Date(y!, m! - 1, 1));

  await db
    .insert(monthlyForecasts)
    .values({
      userId,
      month: monthIsoDate,
      livingExpenseMinor: amountMinor,
      isActual: false,
    })
    .onConflictDoUpdate({
      target: [monthlyForecasts.userId, monthlyForecasts.month],
      set: {
        livingExpenseMinor: amountMinor,
        isActual: false,
        updatedAt: new Date(),
      },
    });
}

export async function updateForecastSettings(
  db: Database,
  userId: string,
  patch: {
    defaultLivingExpenseMinor?: bigint;
    horizonMonths?: number;
    currency?: string;
  },
): Promise<void> {
  await getOrCreateSettings(db, userId);
  await db
    .update(forecastSettings)
    .set({ ...patch, updatedAt: new Date() })
    .where(eq(forecastSettings.userId, userId));
}
